In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([2,3,4])
print(a*b)

[ 2  6 12]


In [3]:
#a=[1,2,3]
#b=[3,4,5]
#we cant multiply directly in lists 
#print(a*b)

In [5]:
c=np.array([[4,5,6],[7.0,2.0,5.1]])
c.ndim

2

In [6]:
a.dtype
#tells which datatype you are using 

dtype('int32')

In [7]:
#we can specify the datasize in aray itself
a=np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [9]:
#number of bytes in each array item
a.itemsize


2

In [10]:
#dimentions of the array 
#ex c has 2 rows and 3 columns
c.shape

(2, 3)

In [11]:
a.size
#get total size
a.nbytes
#get total number of bytes 

6

# changing specific elements

In [13]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# 3
a[0,-1]# last element of 0 th row
a[0,2]#second element of 0 th row

3

In [15]:
a[0,:]
#to get a first row

array([1, 2, 3])

In [16]:
a[2,:]

array([7, 8, 9])

In [19]:
#[start index ,end index,step size]
a[:0:-1]

array([[7, 8, 9],
       [4, 5, 6]])

In [20]:
a[2,:]=0
print(a)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [26]:
#intialise all zero arrays
a=np.zeros((3,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [29]:
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

In [30]:
np.random.rand(4,2)
#generate random number(0 to 1)  of matrix size 4,2

array([[0.2725274 , 0.4373511 ],
       [0.96976691, 0.43643392],
       [0.93757896, 0.57821249],
       [0.55144967, 0.94487982]])

In [31]:
#randomm integer values
np.random.randint(7)

6

In [33]:
#random integers matrix between 0-7
np.random.randint(7,size=(3,3))

array([[0, 3, 6],
       [4, 3, 1],
       [0, 3, 2]])

In [34]:
np.identity(3)
#print an identity matrix of z=3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr=np.ones((5,5))
print(arr)
z=np.zeros((3,3))
z[1,1]=9
print(z)

arr[1:-1,1:-1]=z
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
####be caarful while copying arrays



In [48]:
a=np.array([1,2,3])
b=a
print(b)
b[0]=100
print(a)


#here value of 'a' array also got changed because b is pinting tiwards a and not copied

[1 2 3]
[100   2   3]


In [49]:
a=np.array([1,2,3])
b=a.copy() # by using .copy method now it is copied
print(b)
b[0]=100
print(a)


[1 2 3]
[1 2 3]


In [50]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [51]:
a+2 # addsevery element by 2

array([3, 4, 5])

In [52]:
a/2 #divides by 2

array([0.5, 1. , 1.5])