In [4]:
import numpy as np
#numerical python

In [5]:
x=np.array([1,2,6,5,4])

In [6]:
x


array([1, 2, 6, 5, 4])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
print(list(np.ones(5)))

[1.0, 1.0, 1.0, 1.0, 1.0]


In [10]:
np.random.random(5)
#random floating pt numbers from 0 to 1

array([0.28492596, 0.83242098, 0.00166575, 0.87799057, 0.35019748])

In [11]:
new_math=np.array([1,2,3])

In [12]:
new_math

array([1, 2, 3])

In [13]:
new_math=new_math + np.ones(3)
#additon of 2 arrays
print(new_math)

[2. 3. 4.]


In [14]:
new_math[2]

4.0

In [15]:
new_math[-1]

4.0

In [16]:
new_math.max()

4.0

In [17]:
 new_math.sum()

9.0

In [18]:
new_math.mean()

3.0

In [19]:
x=np.array([[10,20],[30,40]])
x

array([[10, 20],
       [30, 40]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
x=np.array([1,2,3,7,6,8])
x.reshape(3,2)
#reshapes the array
x.reshape(2,3)

array([[1, 2, 3],
       [7, 6, 8]])

In [28]:
x=np.array([[[10,20],[3,40]],[[50,60],[70,80]]])
x

array([[[10, 20],
        [ 3, 40]],

       [[50, 60],
        [70, 80]]])

In [31]:
np.ones((3,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
kanto=np.array([73,67,43])
johnto=np.array([69,56,80])
monto=np.array([56,90,45])

In [34]:
weights=np.array([0.3,0.4,0.4])

In [46]:
#using normal method we need to multi ply each an de evry element using for loop 

def cropYeild(name):
    result=0
    for x,m in zip(weights,name):
        result+=x*m
    return result

In [37]:
cropYeild(kanto)

65.9

In [38]:
cropYeild(johnto)

75.1

In [39]:
cropYeild(monto)

70.8

In [44]:
#in numpy method we can do it directly without using any loops
#it is faster than normal method
def numpyCropYeild(name):
    result=0
    result=weights*name
    return sum(result)

In [48]:
numpyCropYeild(johnto)


75.1

In [50]:
numpyCropYeild(monto)


70.8

In [53]:
numpyCropYeild(kanto)

65.9